name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5
        with:
          python-version: 3.9
      - name: Install build tools
        run: python3 -m pip install --upgrade build
      - name: Test python build
        run: python3 -m build
      - name: Upload built artifacts
        uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # v4
        with:
          name: builds
          path: dist
          if-no-files-found: error
      - name: Build image
        run: docker-compose build
      - name: Run plugin
        run: docker-compose up
      - name: Extract coverage data
        run: |
          docker create --name test ghcr.io/arcalot/arcaflow-plugin-wait:latest
          docker cp test:/htmlcov .
          docker rm test
      - name: Publish coverage report to job summary
        run: |
          pip install html2text
          html2text --ignore-images --ignore-links -b 0 htmlcov/index.html >> $GITHUB_STEP_SUMMARY
      - name: Upload coverage results
        uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # v4
        with:
          name: coverage
          path: htmlcov
          if-no-files-found: error
